<?php

function uuid4()
{
    $uuid = sprintf('%04x%04x-%04x-%04x-%04x-%04x%04x%04x', mt_rand(0, 0xffff), mt_rand(0, 0xffff), mt_rand(0, 0xffff), mt_rand(0, 0x0fff) | 0x4000, mt_rand(0, 0x3fff) | 0x8000, mt_rand(0, 0xffff), mt_rand(0, 0xffff), mt_rand(0, 0xffff));
    return $uuid;
}

function createJSONLDOutput()
{
    $year = date("Y");
    $doc = <<<jsonld
{
  "@graph" : [
  {
      "@id": "https://github.com/lszeremeta/MEgen",
      "@type": "http://schema.org/Organization",
      "http://schema.org/name": "MEgen"
  },
  {
      "@id": "#",
      "@type": "http://schema.org/Dataset",
      "http://schema.org/about": {
        "@id": "https://github.com/lszeremeta/MEgen"
      },
      "http://schema.org/description": "This is a dataset of molecules generated by MEgen.",
      "http://schema.org/keywords": [
        "molecules",
        "cheminformatics",
        "chemical compounds"
      ],
      "http://schema.org/license": {
        "@id": "http://opendatacommons.org/licenses/pddl/1.0/"
      },
      "http://schema.org/name": "Molecules",
      "http://schema.org/creator": {
        "@id": "https://github.com/lszeremeta/MEgen"
      },
      "http://schema.org/temporal": "$year",
      "http://schema.org/url": "https://github.com/lszeremeta/MEgen"
  },

jsonld;
    $count = isset($_POST['count']) ? $_POST['count'] : '1';
    for ($i = 1; $i <= $count; $i++) {
        $namething1 = isset($_POST["name-thing-$i"]) ? $_POST["name-thing-$i"] : '';
        if ($namething1 == 'iri') {
            $subject1 = isset($_POST["iri-$i"]) ? $_POST["iri-$i"] : '';
        } elseif ($namething1 == 'uuid') {
            $subject1 = 'urn:uuid:' . uuid4();
        } else {
            $subject1 = '_:' . uniqid();
        }
        if ($subject1 == '') {
            $subject1 = '_:' . uniqid();
        }
        $identifier1 = isset($_POST["identifier-$i"]) ? $_POST["identifier-$i"] : '';
        $name1 = isset($_POST["name-$i"]) ? $_POST["name-$i"] : '';
        $inchikey1 = isset($_POST["inchikey-$i"]) ? $_POST["inchikey-$i"] : '';
        $inchi1 = isset($_POST["inchi-$i"]) ? $_POST["inchi-$i"] : '';
        $smiles1 = isset($_POST["smiles-$i"]) ? $_POST["smiles-$i"] : '';
        $url1 = isset($_POST["url-$i"]) ? $_POST["url-$i"] : '';
        $iupacname1 = isset($_POST["iupac-name-$i"]) ? $_POST["iupac-name-$i"] : '';
        $molecularformula1 = isset($_POST["molecular-formula-$i"]) ? $_POST["molecular-formula-$i"] : '';
        $molecularweight1 = isset($_POST["molecular-weight-$i"]) ? $_POST["molecular-weight-$i"] : '';
        $monoisotopicmolecularweight1 = isset($_POST["monoisotopic-molecular-weight-$i"]) ? $_POST["monoisotopic-molecular-weight-$i"] : '';
        $description1 = isset($_POST["description-$i"]) ? $_POST["description-$i"] : '';
        $disambiguatingdescription1 = isset($_POST["disambiguating-description-$i"]) ? $_POST["disambiguating-description-$i"] : '';
        $image1 = isset($_POST["image-$i"]) ? $_POST["image-$i"] : '';
        $alternatename1 = isset($_POST["alternate-name-$i"]) ? $_POST["alternate-name-$i"] : '';
        $sameas1 = isset($_POST["same-as-$i"]) ? $_POST["same-as-$i"] : '';

        $doc = $doc . "  {";
        $doc = $doc . "\n  \"@id\" : \"$subject1\",";
        $doc = $doc . "\n  \"@type\" : \"https://schema.org/MolecularEntity\",";
        if ($identifier1 != '') {
            $doc = $doc . "\n  \"identifier\" : \"$identifier1\",";
        }
        if ($name1 != '') {
            $doc = $doc . "\n  \"name\" : \"$name1\",";
        }
        if ($inchikey1 != '') {
            $doc = $doc . "\n  \"inChIKey\" : \"$inchikey1\",";
        }
        if ($inchi1 != '') {
            $doc = $doc . "\n  \"inChI\" : \"$inchi1\",";
        }
        if ($smiles1 != '') {
            $doc = $doc . "\n  \"smiles\" : \"$smiles1\",";
        }
        if ($url1 != '') {
            $doc = $doc . "\n  \"url\" : \"$url1\",";
        }
        if ($iupacname1 != '') {
            $doc = $doc . "\n  \"iupacName\" : \"$iupacname1\",";
        }
        if ($molecularformula1 != '') {
            $doc = $doc . "\n  \"molecularFormula\" : \"$molecularformula1\",";
        }
        if ($molecularweight1 != '') {
            $doc = $doc . "\n  \"molecularWeight\" : \"$molecularweight1\",";
        }
        if ($monoisotopicmolecularweight1 != '') {
            $doc = $doc . "\n  \"monoisotopicMolecularWeight\" : \"$monoisotopicmolecularweight1\",";
        }
        if ($description1 != '') {
            $doc = $doc . "\n  \"description\" : \"$description1\",";
        }
        if ($disambiguatingdescription1 != '') {
            $doc = $doc . "\n  \"disambiguatingDescription\" : \"$disambiguatingdescription1\",";
        }
        if ($image1 != '') {
            $doc = $doc . "\n  \"image\" : \"$image1\",";
        }
        if ($alternatename1 != '') {
            $doc = $doc . "\n  \"alternateName\" : \"$alternatename1\",";
        }
        if ($sameas1 != '') {
            $doc = $doc . "\n  \"sameAs\" : \"$sameas1\",";
        }

        $doc = substr($doc, 0, -1);
        $doc = $doc . "  },";
    }
    $doc = substr($doc, 0, -1);

    $doc = $doc . <<<jsonld
 ],
  "@context" : {
    "identifier" : {
      "@id" : "https://schema.org/identifier"
    },
    "name" : {
      "@id" : "https://schema.org/name"
    },
    "inChIKey" : {
      "@id" : "https://schema.org/inChIKey"
    },
    "inChI" : {
      "@id" : "https://schema.org/inChI"
    },
    "smiles" : {
      "@id" : "https://schema.org/smiles"
    },
    "url" : {
      "@id" : "https://schema.org/url"
    },
    "iupacName" : {
      "@id" : "https://schema.org/iupacName"
    },
    "molecularFormula" : {
      "@id" : "https://schema.org/molecularFormula"
    },
    "molecularWeight" : {
      "@id" : "https://schema.org/molecularWeight"
    },
    "monoisotopicMolecularWeight" : {
      "@id" : "https://schema.org/monoisotopicMolecularWeight"
    },
    "description" : {
      "@id" : "https://schema.org/description"
    },
    "disambiguatingDescription" : {
      "@id" : "https://schema.org/disambiguatingDescription"
    },
    "image" : {
      "@id" : "https://schema.org/image"
    },
    "alternateName" : {
      "@id" : "https://schema.org/alternateName"
    },
    "sameAs" : {
      "@id" : "https://schema.org/sameAs"
    },
    "schema" : "https://schema.org/"
  }
}

jsonld;

    return $doc;
}

function createRDFaOutput()
{
    $year = date("Y");
    $doc = <<<rdfa
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Example Document</title>
  </head>
  <body vocab="http://schema.org/">

rdfa;

    $ds = <<<ds
  <div prefix="schema: http://schema.org/">
    <div typeof="schema:Dataset">
      <div rel="schema:creator">
        <div typeof="schema:Organization" about="https://github.com/lszeremeta/MEgen">
          <div property="schema:name" content="MEgen"></div>
        </div>
      </div>
      <div property="schema:keywords" content="cheminformatics"></div>
      <div property="schema:keywords" content="molecules"></div>
      <div property="schema:keywords" content="chemical compounds"></div>
      <div property="schema:temporal" content="$year"></div>
      <div property="schema:name" content="Molecules"></div>
      <div rel="schema:license" resource="http://opendatacommons.org/licenses/pddl/1.0/"></div>
      <div property="schema:description" content="This is a dataset of molecules generated by MEgen."></div>
      <div rel="schema:about" resource="https://github.com/lszeremeta/MEgen"></div>
      <div property="schema:url" content="https://github.com/lszeremeta/MEgen"></div>
    </div>
  </div>

ds;
    $doc = $doc . $ds;
    $count = isset($_POST['count']) ? $_POST['count'] : '1';
    for ($i = 1; $i <= $count; $i++) {
        $namething1 = isset($_POST["name-thing-$i"]) ? $_POST["name-thing-$i"] : '';
        if ($namething1 == 'iri') {
            $subject1 = isset($_POST["iri-$i"]) ? $_POST["iri-$i"] : '';
        } elseif ($namething1 == 'uuid') {
            $subject1 = 'urn:uuid:' . uuid4();
        } else {
            $subject1 = '_:' . uniqid();
        }
        if ($subject1 == '') {
            $subject1 = '_:' . uniqid();
        }
        $identifier1 = isset($_POST["identifier-$i"]) ? htmlspecialchars($_POST["identifier-$i"]) : '';
        $name1 = isset($_POST["name-$i"]) ? htmlspecialchars($_POST["name-$i"]) : '';
        $inchikey1 = isset($_POST["inchikey-$i"]) ? htmlspecialchars($_POST["inchikey-$i"]) : '';
        $inchi1 = isset($_POST["inchi-$i"]) ? htmlspecialchars($_POST["inchi-$i"]) : '';
        $smiles1 = isset($_POST["smiles-$i"]) ? htmlspecialchars($_POST["smiles-$i"]) : '';
        $url1 = isset($_POST["url-$i"]) ? htmlspecialchars($_POST["url-$i"]) : '';
        $iupacname1 = isset($_POST["iupac-name-$i"]) ? htmlspecialchars($_POST["iupac-name-$i"]) : '';
        $molecularformula1 = isset($_POST["molecular-formula-$i"]) ? htmlspecialchars($_POST["molecular-formula-$i"]) : '';
        $molecularweight1 = isset($_POST["molecular-weight-$i"]) ? htmlspecialchars($_POST["molecular-weight-$i"]) : '';
        $monoisotopicmolecularweight1 = isset($_POST["monoisotopic-molecular-weight-$i"]) ? htmlspecialchars($_POST["monoisotopic-molecular-weight-$i"]) : '';
        $description1 = isset($_POST["description-$i"]) ? htmlspecialchars($_POST["description-$i"]) : '';
        $disambiguatingdescription1 = isset($_POST["disambiguating-description-$i"]) ? htmlspecialchars($_POST["disambiguating-description-$i"]) : '';
        $image1 = isset($_POST["image-$i"]) ? htmlspecialchars($_POST["image-$i"]) : '';
        $alternatename1 = isset($_POST["alternate-name-$i"]) ? htmlspecialchars($_POST["alternate-name-$i"]) : '';
        $sameas1 = isset($_POST["same-as-$i"]) ? htmlspecialchars($_POST["same-as-$i"]) : '';

        $doc = $doc . "    <div typeof='schema:MolecularEntity' about='$subject1'>";
        if ($identifier1 != '') {
            $doc = $doc . "\n      <div property='schema:identifier'>$identifier1</div>";
        }
        if ($name1 != '') {
            $doc = $doc . "\n      <div property='schema:name'>$name1</div>";
        }
        if ($inchikey1 != '') {
            $doc = $doc . "\n      <div property='schema:inChIKey'>$inchikey1</div>";
        }
        if ($inchi1 != '') {
            $doc = $doc . "\n      <div property='schema:inChI'>$inchi1</div>";
        }
        if ($smiles1 != '') {
            $doc = $doc . "\n      <div property='schema:smiles'>$smiles1</div>";
        }
        if ($url1 != '') {
            $doc = $doc . "\n      <a rel='schema:url' href='$url1'>$url1</a>";
        }
        if ($iupacname1 != '') {
            $doc = $doc . "\n      <div property='schema:iupacName'>$iupacname1</div>";
        }
        if ($molecularformula1 != '') {
            $doc = $doc . "\n      <div property='schema:molecularFormula'>$molecularformula1</div>";
        }
        if ($molecularweight1 != '') {
            $doc = $doc . "\n      <div property='schema:molecularWeight'>$molecularweight1</div>";
        }
        if ($monoisotopicmolecularweight1 != '') {
            $doc = $doc . "\n      <div property='schema:monoisotopicMolecularWeight'>$monoisotopicmolecularweight1</div>";
        }
        if ($description1 != '') {
            $doc = $doc . "\n      <div property='schema:description'>$description1</div>";
        }
        if ($disambiguatingdescription1 != '') {
            $doc = $doc . "\n      <div property='schema:disambiguatingDescription'>$disambiguatingdescription1</div>";
        }
        if ($image1 != '') {
            $doc = $doc . "\n      <img src='$image1' alt='Image of the Molecule$i' rel='schema:image'>";
        }
        if ($alternatename1 != '') {
            $doc = $doc . "\n      <div property='schema:alternateName'>$alternatename1</div>";
        }
        if ($sameas1 != '') {
            $doc = $doc . "\n      <a href='$sameas1' rel='schema:sameAs'>$sameas1</a>";
        }

        $doc = $doc . "\n    </div>\n";
    }

    return $doc . "\n  </body>\n</html>";
}

function createMicrodataOutput()
{
    $year = date("Y");
    $doc = <<<microdata
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Example Document</title>
  </head>
  <body>

microdata;

    $ds = <<<ds

  <div itemscope="" itemtype="https://schema.org/Dataset">
    <div itemprop="name" content="Molecules"></div>
    <div itemprop="keywords" content="cheminformatics"></div>
    <div itemprop="keywords" content="molecules"></div>
    <div itemprop="keywords" content="chemical compounds"></div>
    <div itemprop="temporal" content="$year"></div>
    <div itemprop="url" content="https://github.com/lszeremeta/MEgen"></div>
    <div itemprop="description" content="This is a dataset of molecules generated by MEgen."></div>
    <div itemprop="creator" itemscope="" itemtype="https://schema.org/Organization">
      <div itemprop="name" content="MEgen"></div>
    </div>
    <div itemprop="license" content="http://opendatacommons.org/licenses/pddl/1.0/"></div>
  </div>

ds;

    $doc = $doc . $ds;
    $count = isset($_POST['count']) ? $_POST['count'] : '1';
    for ($i = 1; $i <= $count; $i++) {
        $namething1 = isset($_POST["name-thing-$i"]) ? $_POST["name-thing-$i"] : '';
        if ($namething1 == 'iri') {
            $subject1 = isset($_POST["iri-$i"]) ? $_POST["iri-$i"] : '';
        } elseif ($namething1 == 'uuid') {
            $subject1 = 'urn:uuid:' . uuid4();
        } else {
            $subject1 = '_:' . uniqid();
        }
        if ($subject1 == '') {
            $subject1 = '_:' . uniqid();
        }
        $identifier1 = isset($_POST["identifier-$i"]) ? htmlspecialchars($_POST["identifier-$i"]) : '';
        $name1 = isset($_POST["name-$i"]) ? htmlspecialchars($_POST["name-$i"]) : '';
        $inchikey1 = isset($_POST["inchikey-$i"]) ? htmlspecialchars($_POST["inchikey-$i"]) : '';
        $inchi1 = isset($_POST["inchi-$i"]) ? htmlspecialchars($_POST["inchi-$i"]) : '';
        $smiles1 = isset($_POST["smiles-$i"]) ? htmlspecialchars($_POST["smiles-$i"]) : '';
        $url1 = isset($_POST["url-$i"]) ? htmlspecialchars($_POST["url-$i"]) : '';
        $iupacname1 = isset($_POST["iupac-name-$i"]) ? htmlspecialchars($_POST["iupac-name-$i"]) : '';
        $molecularformula1 = isset($_POST["molecular-formula-$i"]) ? htmlspecialchars($_POST["molecular-formula-$i"]) : '';
        $molecularweight1 = isset($_POST["molecular-weight-$i"]) ? htmlspecialchars($_POST["molecular-weight-$i"]) : '';
        $monoisotopicmolecularweight1 = isset($_POST["monoisotopic-molecular-weight-$i"]) ? htmlspecialchars($_POST["monoisotopic-molecular-weight-$i"]) : '';
        $description1 = isset($_POST["description-$i"]) ? htmlspecialchars($_POST["description-$i"]) : '';
        $disambiguatingdescription1 = isset($_POST["disambiguating-description-$i"]) ? htmlspecialchars($_POST["disambiguating-description-$i"]) : '';
        $image1 = isset($_POST["image-$i"]) ? htmlspecialchars($_POST["image-$i"]) : '';
        $alternatename1 = isset($_POST["alternate-name-$i"]) ? htmlspecialchars($_POST["alternate-name-$i"]) : '';
        $sameas1 = isset($_POST["same-as-$i"]) ? htmlspecialchars($_POST["same-as-$i"]) : '';

        $doc = $doc . "    <div itemscope itemtype='http://schema.org/MolecularEntity' itemid='$subject1'>";
        if ($identifier1 != '') {
            $doc = $doc . "\n      <div itemprop='identifier'>$identifier1</div>";
        }
        if ($name1 != '') {
            $doc = $doc . "\n      <div itemprop='name'>$name1</div>";
        }
        if ($inchikey1 != '') {
            $doc = $doc . "\n      <div itemprop='inChIKey'>$inchikey1</div>";
        }
        if ($inchi1 != '') {
            $doc = $doc . "\n      <div itemprop='inChI'>$inchi1</div>";
        }
        if ($smiles1 != '') {
            $doc = $doc . "\n      <div itemprop='smiles'>$smiles1</div>";
        }
        if ($url1 != '') {
            $doc = $doc . "\n      <a href='$url1' itemprop='url'>$url1</a>";
        }
        if ($iupacname1 != '') {
            $doc = $doc . "\n      <div itemprop='iupacName'>$iupacname1</div>";
        }
        if ($molecularformula1 != '') {
            $doc = $doc . "\n      <div itemprop='molecularFormula'>$molecularformula1</div>";
        }
        if ($molecularweight1 != '') {
            $doc = $doc . "\n      <div itemprop='molecularWeight'>$molecularweight1</div>";
        }
        if ($monoisotopicmolecularweight1 != '') {
            $doc = $doc . "\n      <div itemprop='monoisotopicMolecularWeight'>$monoisotopicmolecularweight1</div>";
        }
        if ($description1 != '') {
            $doc = $doc . "\n      <div itemprop='description'>$description1</div>";
        }
        if ($disambiguatingdescription1 != '') {
            $doc = $doc . "\n      <div itemprop='disambiguatingDescription'>$disambiguatingdescription1</div>";
        }
        if ($image1 != '') {
            $doc = $doc . "\n      <img src='$image1' alt='Image of the Molecule$i' itemprop='image'>";
        }
        if ($alternatename1 != '') {
            $doc = $doc . "\n      <div itemprop='alternateName'>$alternatename1</div>";
        }
        if ($sameas1 != '') {
            $doc = $doc . "\n      <a href='$sameas1' itemprop='sameAs'>$sameas1</a>";
        }

        $doc = $doc . "\n    </div>\n";
    }
    return $doc . "\n  </body>\n</html>";
}

$format = $_POST['output-format'];

if ($format === "JSON-LD with HTML") {
    $doc = <<<jsonld_html_start
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Example Document</title>
    <script type="application/ld+json">

jsonld_html_start;

    $doc = $doc . createJSONLDOutput() . <<<jsonld_html_end
    </script>
  </head>
</html>
jsonld_html_end;

    header('Content-type: text/html');
    header('Content-Disposition: attachment; filename="jsonld.html"');
} elseif ($format === "JSON-LD") {
    $doc = createJSONLDOutput();

    header('Content-type: application/ld+json');
    header('Content-Disposition: attachment; filename="jsonld.jsonld"');
} elseif ($format === "RDFa") {
    $doc = createRDFaOutput();

    header('Content-type: text/html');
    header('Content-Disposition: attachment; filename="rdfa.html"');
} elseif ($format === "Microdata") {
    $doc = createMicrodataOutput();

    header('Content-type: text/html');
    header('Content-Disposition: attachment; filename="microdata.html"');
}

echo $doc;

