name: Release

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  test:
    name: jMeter tests
    runs-on: ubuntu-latest
    services:
      megen:
        image: php:8.0-apache
        ports:
          - 80:80
        volumes:
          - ${{ github.workspace }}:/var/www/html/
    steps:
      - uses: actions/checkout@v2
      - name: Run JMeter Tests
        uses: rbhadti94/apache-jmeter-action@v0.3.2
        with:
          testFilePath: tests/all.jmx
          outputReportsFolder: reports/
      - uses: actions/upload-artifact@v1
        with:
          name: jmeter-test-results
          path: reports/

  github-release:
    name: GitHub Release
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Create GitHub release draft
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          draft: true

  docker-hub:
    name: Docker Hub
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Prepare
        id: prep
        run: |
          DOCKER_IMAGE=lszeremeta/megen
          VERSION=${GITHUB_REF#refs/tags/v}
          TAGS="${DOCKER_IMAGE}:${VERSION}"
          echo ::set-output name=tags::${TAGS}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.buildx.outputs.name }}
          file: Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.prep.outputs.tags }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
      - name: Update repo description
        uses: peter-evans/dockerhub-description@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASS }}
          repository: lszeremeta/megen

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Get latest code
        uses: actions/checkout@v2
      - name: Wait for concurrent jobs
        uses: softprops/turnstyle@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME_RELEASE }}
          password: ${{ secrets.FTP_PASSWORD_RELEASE }}
          protocol: ftps
          exclude: .git*
            - .git*/**
            - **/.git*/**
            - .dockerignore
            - logo/raw-svg
            - logo/raw-svg/*
            - logo/megen.png
            - Dockerfile
            - tests
            - tests/*
            - LICENSE
            - README.md
            - stack.yml
          security: strict
